### ISSUE TITLE
NMEA0183 V4.11 XDR Transducer IDs are not all capital

### ISSUE THREAD

**Issue by ch-fb** [TwoCanPlugIn/EngineDashboard#3]
Hi there,
If I read the standard correctly, transducer IDs have been defined as e.g. "FreshWater#0"
It seems the plugin has the IDs hard-coded as all-capital versions like "FRESHWATER#0"
Ignoring the case when parsing the transducer ID would accept both versions.
with best regards,
Christian

**Comment by TwoCanPlugIn** [comment]
I don't have access to the actual NMEA standards documents. Seeing as though it seems you have access to the standard, it appears that  I incorrectly assumed that the names were uppercase. At the time some users were using ShipModul & Maretron multiplexers and it seems as they were generating uppercase. It would be an easy fix to ignore the case in the next release, whenever that may be. Sorry I can't offer a time frame.

**Comment by ch-fb** [comment]
thanks, that fix would be great

**Comment by ch-fb** [comment]
have a look there, at page 47:
http://www.marineelectronicsjournal-digital.com/marineelectronicsjournal/january_february_2019
