### ISSUE TITLE
Main and Port Water Temperature not showing in Raspberry Pi 4 64 bit

### ISSUE THREAD

**Issue by biasosoft** [TwoCanPlugIn/EngineDashboard#6]
On a fresh setup of open CPN 5.8.4-1, on a Raspberry PI 4, Raspbian 64 bit, I am sending NMEA183 sentences via a TCP connection with a third party test app.
1. The RMC sentence is correctly parsed and accepted, the XDR test sentence is correctly parsed and accepted.
2. Open CPN correctly uses the position data
3. The Engine-Dashboard with Main Water Temperature and Port Water Temperature does not show any data
4. The test sentence I am sending is copied by Engine Dashboard manual: $IIXDR,P,100300.00,P,ENGINEOIL#0,C,85.0,C,ENGINE#0,U,26.44,V,ALTERNATOR#0*09
5. I am expecting to see water temperature related to ENGINE#0 fields
6. I tried to alter the IIXDR part to YCXDR part but nothing works
7. Browsing the source code of the plugin, it seems that the parser should match the received sentence, so I am stuck
8. The function void dashboard_`pi::HandleXDR(ObservedEvt ev)` should parse the received message correctly and match the part C,85.0,C,ENGINE#0

**Comment by TwoCanPlugIn** [comment]
Hi Luca,

You also need to send a valid RPM sentence. There is a watchdog timer that sets the gauges to zero. If you imagine that turning the key off, the engine isn't running so the gauges are zeroed.

These are examples of valid engine tachometer sentences for a single engine vessel:

$ERXDR,T,1700,R,ENGINE#0*44

or

$ERRPM,E,0,1700,,A*46

And if you want to include Engine Hours, add a XDR sentence element similar to the following:
G,250,,Engine#0

Note that the Port & Starboard gauges are only populated if the "dual engine" option is set in the Engine Dashboard preferences page (under the Appearance tab).

Regards.
________________________________
From: Luca Biasin ***@***.***>
Sent: 03 October 2023 22:23
To: TwoCanPlugIn/EngineDashboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TwoCanPlugIn/EngineDashboard] Main and Port Water Temperature not showing in Raspberry Pi 4 64 bit (Issue #6)


On a fresh setup of open CPN 5.8.4-1, on a Raspberry PI 4, Raspbian 64 bit, I am sending NMEA183 sentences via a TCP connection with a third party test app.

  1.  The RMC sentence is correctly parsed and accepted, the XDR test sentence is correctly parsed and accepted.
  2.  Open CPN correctly uses the position data
  3.  The Engine-Dashboard with Main Water Temperature and Port Water Temperature does not show any data
  4.  The test sentence I am sending is copied by Engine Dashboard manual: $IIXDR,P,100300.00,P,ENGINEOIL#0,C,85.0,C,ENGINE#0,U,26.44,V,ALTERNATOR#0*09
  5.  I am expecting to see water temperature related to ENGINE#0 fields
  6.  I tried to alter the IIXDR part to YCXDR part but nothing works
  7.  Browsing the source code of the plugin, it seems that the parser should match the received sentence, so I am stuck

**Comment by biasosoft** [comment]
Thank you!I’ll try as soon as possibleRegards,Luca--------------------------------Luca BiasinIl giorno 5 ott 2023, alle ore 10:59, TwoCanPlugIn ***@***.***> ha scritto:﻿
Hi Luca,



You also need to send a valid RPM sentence. There is a watchdog timer that sets the gauges to zero. If you imagine that turning the key off, the engine isn't running so the gauges are zeroed.



These are examples of valid engine tachometer sentences for a single engine vessel:



$ERXDR,T,1700,R,ENGINE#0*44



or



$ERRPM,E,0,1700,,A*46



And if you want to include Engine Hours, add a XDR sentence element similar to the following:

G,250,,Engine#0



Note that the Port & Starboard gauges are only populated if the "dual engine" option is set in the Engine Dashboard preferences page (under the Appearance tab).



Regards.

________________________________

From: Luca Biasin ***@***.***>

Sent: 03 October 2023 22:23

To: TwoCanPlugIn/EngineDashboard ***@***.***>

Cc: Subscribed ***@***.***>

Subject: [TwoCanPlugIn/EngineDashboard] Main and Port Water Temperature not showing in Raspberry Pi 4 64 bit (Issue #6)





On a fresh setup of open CPN 5.8.4-1, on a Raspberry PI 4, Raspbian 64 bit, I am sending NMEA183 sentences via a TCP connection with a third party test app.



  1.  The RMC sentence is correctly parsed and accepted, the XDR test sentence is correctly parsed and accepted.

  2.  Open CPN correctly uses the position data

  3.  The Engine-Dashboard with Main Water Temperature and Port Water Temperature does not show any data

  4.  The test sentence I am sending is copied by Engine Dashboard manual: $IIXDR,P,100300.00,P,ENGINEOIL#0,C,85.0,C,ENGINE#0,U,26.44,V,ALTERNATOR#0*09

  5.  I am expecting to see water temperature related to ENGINE#0 fields

  6.  I tried to alter the IIXDR part to YCXDR part but nothing works

  7.  Browsing the source code of the plugin, it seems that the parser should match the received sentence, so I am stuck

**Comment by TwoCanPlugIn** [comment]
Closing as no further responses received or action required.
