### ISSUE TITLE
Dashboard window docks into Opencpn canvas in Multicanvas Mode.

### ISSUE THREAD

**Issue by BerndCirotzki** [TwoCanPlugIn/EngineDashboard#7]
When moving the Engine Dashboard in Opencpn in Mulitcanvas Mode its getting docked in the OpenCPN Window.

https://github.com/TwoCanPlugIn/EngineDashboard/assets/32094108/bb16d4ce-0780-419e-8272-79f3abc82a6f

**Comment by TwoCanPlugIn** [comment]
Hi Bernd,

The engine dashboard is based on an older version of the original dashboard plugin. Does the current dashboard plugin exhibit the same behaviour in multi canvas mode ?

If not, then the fix, which unfortunately is a significant amount of work, is to rebase the engine dashboard on the new code base of the dashboard. I don't have a short term plan for that (not enough time), however if that is the fix, it has the benefit of also introducing support for Android so certainly something I would contemplate for the future.

Thanks for the heads up.

Regards.


________________________________
From: Bernd Cirotzki ***@***.***>
Sent: 29 January 2024 15:55
To: TwoCanPlugIn/EngineDashboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TwoCanPlugIn/EngineDashboard] Dashboard window docks into Opencpn canvas in Multicanvas Mode. (Issue #7)


When moving the Engine Dashboard in Opencpn in Mulitcanvas Mode its getting docked in the OpenCPN Window.

https://github.com/TwoCanPlugIn/EngineDashboard/assets/32094108/bb16d4ce-0780-419e-8272-79f3abc82a6f

**Comment by BerndCirotzki** [comment]
Ok, I found the reason of the problem .... But I don't understand why it fix this. 

// wxWS_EX_VALIDATE_RECURSIVELY required to push events to parents
DashboardWindow::DashboardWindow(wxWindow *pparent, wxWindowID id, wxAuiManager *auimgr,
        dashboard_pi* plugin, int orient, DashboardWindowContainer* mycont) :
        wxWindow(pparent, id, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE, _T("Dashboard")) {

... change to :

DashboardWindow::DashboardWindow(wxWindow *pparent, wxWindowID id, wxAuiManager *auimgr,
        dashboard_pi* plugin, int orient, DashboardWindowContainer* mycont) :
	    wxWindow(pparent, id, wxDefaultPosition, wxDefaultSize, 0) {

I hope it would help !

Regards.

**Comment by TwoCanPlugIn** [comment]
Hi Bernd,

Great, I'll have a look at this. Thanks very much.

Long term, I should update the underlying code base to the current Dashboard plugin, at least to pick up support for platforms such as Android.

Kind regards
________________________________

**Comment by TwoCanPlugIn** [comment]
Hi Bernd,

I've built an updated version v1.7, with your proposed fix.

You can download the tarball for your specific OS from the following link, then just use the "import plugin" option

https://cloudsmith.io/~steven-adler/repos/engineplugin-beta/packages/


The difference in the fix seems to be twofold,

changing the wxBORDER_NONE to 0 (which is actually wxBORDER_DEFAULT) is just a flag for what border style to use. There is another flag wxWS_EX_VALIDATE_RECURSIVELY which is mentioned in a comment at the top, but is unused, which if set would make wxWidgets validate calls recursively into child windows. I've no idea how, if at all that flag relates to OpenCPN's Multi Canvas.

Secondly, the last parameter _T("Dashboard"), just gives a name to the Window, so again I'm unsure how this relates the problem, unless something weird happens with Window Names in Multi Canvas mode.

Let me know if the fix works, and I'll consider updating the master catalogue.

Thanks for your help.
________________________________

**Comment by BerndCirotzki** [comment]
works 👍 

thanks

**Comment by TwoCanPlugIn** [comment]
Thanks very much to you for not only reporting the bug, but also proposing the fix!

I'll get the plugin manager catalogue updated shortly.

Regards.
________________________________
