### ISSUE TITLE
Display of engine hours inconsistent

### ISSUE THREAD

**Issue by aviatorhh** [TwoCanPlugIn/EngineDashboard#9]
The engine hour windows loses its value intermittently (dashes instead of value). There is a 10Hz NMEA2000 source and the engine speed is displayed correctly.
Maybe increase a timeout value?
The value also only displays full hours and now decimal values (always .0) even though it is displayed.

![Screenshot 2024-05-02 at 18 46 37](https://github.com/TwoCanPlugIn/EngineDashboard/assets/13214417/b849296f-2f10-47f9-b831-cf2f7d890370)
![Screenshot 2024-05-02 at 18 46 17](https://github.com/TwoCanPlugIn/EngineDashboard/assets/13214417/38790620-10cf-468d-89b7-e4b3dab9e6b4)

**Comment by TwoCanPlugIn** [comment]
Re not displaying decimal engine hours, probably due to the following:

```
if (IsDataValid(totalEngineHours)) {
				SendSentenceToAllInstruments(OCPN_DBP_STC_PORT_ENGINE_HOURS, totalEngineHours / 3600, "Hrs");
}
```
should probably change to 
`totalEngineHours / 3600.0`
to force a double rather than an unsigned int.

Something to consider fixing for the next version.

Re the intermittent display of engine hours, the RPM gauge timeout is 5 seconds. At your 10Hz rate the watchdog should not be timing out. If it was timing out, the tachometer and other engine related gauges (oil pressure, water temp etc.) should also zero out.

Do you have a log of the engine data ? I'm inclined to think there is something intermittent in the engine dynamic data messages.

**Comment by aviatorhh** [comment]
It could be a kind of performance issue. On a slow linux testing system I sometimes have got the lost display of engine hours. On a RPi4 machine it seems to be steady.

**Comment by aviatorhh** [comment]
I have found the issue finally. I had two connections running - one CAN and one SK. As SK does not seem to provide engine hours but CAN does, the plugin seems not to prioritize somehow and therefore SK data sometimes overcomes the CAN data and no engine hours are displayed. I think I will have to do some filtering somewhere.
Ready for closure from my side at least for the intermittent display. Regarding the decimal issue I have placed a pull request.

**Comment by TwoCanPlugIn** [comment]
Well done on tracking down the cause of the intermittent display.

The plugin does not perform any filtering or prioritization. It was based on the existing Dashboard plugin which relies on OpenCPN to do filtering & prioritization for Dashboard related data (position, speed, wind, dept etc.) but alas no filtering for engine related data.

Kind of surprised SignalK doesn't do engine hours, I thought it did. I'll have a deeper look. 

Thanks for the PR, once I've figured out the platform build issues, I'll merge and get around to releasing an updated version. No promises on a timeframe though.

Regards.

**Comment by aviatorhh** [comment]
Well, you are right actually. The SK path is "propulsion.port.runTime" and it sits in your code (and even in my PR). But when I run on SK and no n2k then no engine hours are displayed. I might take a look at it and may submit a fix.

**Comment by aviatorhh** [comment]
I fixed it. I have changed "GetJsonDouble(value)" to "value.AsInt()". You may want to verify.
